In [21]:
import pandas as pd

In [42]:
#Thanks to fbref.com for statistics. Link: https://fbref.com/en/comps/9/stats/Premier-League-Stats
#Create Dataframe of basic premier league statistics / player statistics
premier_league_teams = pd.read_csv("premier_league_team_statistics.csv")
premier_league_players = pd.read_csv("premier_league_player_statistics.csv")

display(premier_league_teams)
display(premier_league_players)



#create dictionary that contains dataframes for each teams squad
teams = list(premier_league_teams["Squad"])
team_squads = {}
for team in teams:
    team_squads[team] = premier_league_players.loc[premier_league_players["Squad"] == team, :] #take a series of each player that has team = Squad. should contain all players from team

print(team_squads.get("Arsenal")["Player"])

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,...,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,Arsenal,26,25.4,59.5,35,385,3150,35.0,79,60,...,2.26,1.71,3.97,2.17,3.89,1.93,1.43,3.36,1.85,3.28
1,Aston Villa,26,27.8,50.0,35,385,3150,35.0,44,31,...,1.26,0.89,2.14,1.17,2.06,1.28,0.99,2.27,1.22,2.20
2,Bournemouth,31,27.2,39.8,35,385,3150,35.0,37,24,...,1.06,0.69,1.74,1.06,1.74,1.05,0.77,1.82,1.05,1.82
3,Brentford,25,27.0,44.0,35,385,3150,35.0,50,30,...,1.43,0.86,2.29,1.23,2.09,1.45,0.96,2.42,1.27,2.24
4,Brighton,27,27.3,60.7,33,363,2970,33.0,59,38,...,1.79,1.15,2.94,1.61,2.76,1.97,1.39,3.36,1.84,3.22
5,Chelsea,32,27.3,58.7,34,374,3060,34.0,34,25,...,1.00,0.74,1.74,0.91,1.65,1.26,0.97,2.23,1.19,2.16
6,Crystal Palace,26,27.6,45.3,35,385,3150,35.0,33,25,...,0.94,0.71,1.66,0.91,1.63,0.99,0.74,1.73,0.92,1.66
7,Everton,28,27.4,42.9,35,385,3150,35.0,30,23,...,0.86,0.66,1.51,0.77,1.43,1.16,0.83,1.99,1.09,1.92
8,Fulham,29,29.0,48.4,35,385,3150,35.0,47,29,...,1.34,0.83,2.17,1.23,2.06,1.18,0.73,1.91,1.03,1.75
9,Leeds United,29,25.9,47.3,35,385,3150,35.0,41,29,...,1.17,0.83,2.00,1.14,1.97,1.23,0.85,2.08,1.18,2.04
10,Leicester City,28,26.9,48.8,35,385,3150,35.0,47,34,...,1.34,0.97,2.31,1.26,2.23,1.39,1.05,2.44,1.25,2.31
11,Liverpool,27,28.2,60.3,35,385,3150,35.0,63,51,...,1.80,1.46,3.26,1.74,3.20,1.88,1.45,3.33,1.79,3.24
12,Manchester City,23,28.0,64.9,34,374,3060,34.0,87,65,...,2.56,1.91,4.47,2.29,4.21,2.16,1.55,3.71,1.93,3.49
13,Manchester Utd,26,27.7,54.1,34,374,3060,34.0,47,37,...,1.38,1.09,2.47,1.32,2.41,1.62,1.28,2.90,1.57,2.85
14,Newcastle Utd,26,28.1,52.2,34,374,3060,34.0,58,38,...,1.71,1.12,2.82,1.59,2.71,1.83,1.37,3.20,1.74,3.11
15,Nott'ham Forest,33,27.3,38.6,35,385,3150,35.0,32,19,...,0.91,0.54,1.46,0.83,1.37,1.06,0.70,1.76,0.92,1.63
16,Southampton,32,25.4,45.4,35,385,3150,35.0,31,21,...,0.89,0.60,1.49,0.83,1.43,1.00,0.76,1.76,0.91,1.67
17,Tottenham,27,28.4,49.7,35,385,3150,35.0,62,42,...,1.77,1.20,2.97,1.66,2.86,1.48,1.12,2.60,1.37,2.49
18,West Ham,25,29.0,41.2,35,385,3150,35.0,37,21,...,1.06,0.60,1.66,0.89,1.49,1.30,0.84,2.13,1.14,1.98
19,Wolves,31,27.5,49.9,35,385,3150,35.0,27,12,...,0.77,0.34,1.11,0.69,1.03,0.99,0.69,1.68,0.92,1.61

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Matches,-9999
0,1,Brenden Aaronson,us USA,MFFW,Leeds United,22-200,2000,33,28,2307,...,0.16,0.04,0.16,0.14,0.17,0.31,0.14,0.31,Matches,5bc43860
1,2,Che Adams,sct SCO,FW,Southampton,26-301,1996,28,23,1992,...,0.36,0.23,0.36,0.30,0.13,0.42,0.30,0.42,Matches,f2bf1b0f
2,3,Tyler Adams,us USA,MF,Leeds United,24-085,1999,24,24,2156,...,0.00,0.00,0.00,0.00,0.06,0.06,0.00,0.06,Matches,2b09d998
3,4,Tosin Adarabioyo,eng ENG,DF,Fulham,25-228,1997,22,20,1815,...,0.05,0.05,0.05,0.03,0.02,0.05,0.03,0.05,Matches,c81d773d
4,5,Nayef Aguerd,ma MAR,DF,West Ham,27-041,1996,16,15,1415,...,0.13,0.13,0.13,0.14,0.03,0.17,0.14,0.17,Matches,288e1e13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,553,Jordan Zemura,zw ZIM,DF,Bournemouth,23-177,1999,19,17,1454,...,0.06,0.00,0.06,0.02,0.11,0.14,0.02,0.14,Matches,e8271ad9
553,554,Oleksandr Zinchenko,ua UKR,DF,Arsenal,26-146,1996,27,26,2118,...,0.13,0.04,0.13,0.06,0.06,0.12,0.06,0.12,Matches,51cf8561
554,555,Hakim Ziyech,ma MAR,FWMF,Chelsea,30-052,1993,16,6,634,...,0.28,0.00,0.28,0.08,0.26,0.35,0.08,0.35,Matches,6622454d
555,556,Kurt Zouma,fr FRA,DF,West Ham,28-195,1994,24,23,1944,...,0.09,0.09,0.09,0.10,0.00,0.11,0.10,0.11,Matches,ce4246f5
556,557,Martin Ødegaard,no NOR,MF,Arsenal,24-144,1998,34,34,2887,...,0.69,0.47,0.69,0.31,0.24,0.54,0.31,0.54,Matches,79300479

137      Gabriel Dos Santos
152          Mohamed Elneny
224             Rob Holding
241           Gabriel Jesus
248                Jorginho
265            Jakub Kiwior
315              Marquinhos
317              Martinelli
359            Reiss Nelson
365           Eddie Nketiah
368           Ethan Nwaneri
388           Thomas Partey
408          Aaron Ramsdale
439             Bukayo Saka
441          William Saliba
443    Albert Sambi Lokonga
469        Emile Smith Rowe
470           Cédric Soares
499          Kieran Tierney
501       Takehiro Tomiyasu
509        Leandro Trossard
518            Fabio Vieira
533               Ben White
546            Granit Xhaka
553     Oleksandr Zinchenko
556         Martin Ødegaard
Name: Player, dtype: object